services:
  bookshelf-api-gateway:
    build:
      context: bookshelf-api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./.config/bookshelf-api-gateway/nginx:/etc/nginx/conf.d:ro
    networks:
      - gateway-network
      - app-network

  bookshelf-pg:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_BOOKSHELF_USER}
      POSTGRES_PASSWORD: ${POSTGRES_BOOKSHELF_PASSWORD}
      POSTGRES_DB: ${POSTGRES_BOOKSHELF_DATABASE}
    networks:
      - app-network

  bookshelf-redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - app-network

  bookshelf-rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq-node
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network

  bookshelf-backend:
    build:
      context: bookshelf-backend
      dockerfile: Dockerfile
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx128m -Xms128m
      - POSTGRES_BOOKSHELF_HOST=bookshelf-pg
      - POSTGRES_BOOKSHELF_PORT=5432
      - POSTGRES_BOOKSHELF_DATABASE=${POSTGRES_BOOKSHELF_DATABASE}
      - POSTGRES_BOOKSHELF_USERNAME=${POSTGRES_BOOKSHELF_USER}
      - POSTGRES_BOOKSHELF_PASSWORD=${POSTGRES_BOOKSHELF_PASSWORD}
      - REDIS_HOST=bookshelf-redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=bookshelf-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    depends_on:
      bookshelf-pg:
        condition: service_started
      bookshelf-redis:
        condition: service_started
      bookshelf-rabbitmq:
        condition: service_healthy

  bookshelf-frontend:
    build:
      context: bookshelf-frontend
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  gateway-network:
    external: true
  app-network:
    driver: bridge

volumes:
  bookshelf-pg-data:
  rabbitmq-data:
  redis-data: