version: '3.8'

services:

  bookshelf-api-gateway:
    build:
      context: bookshelf-api-gateway
      dockerfile: Dockerfile
    container_name: bookshelf-api-gateway
    volumes:
      - ./.config/bookshelf-api-gateway/nginx:/etc/nginx/conf.d:ro
      - ./.config/bookshelf-api-gateway/letsencrypt:/etc/letsencrypt:ro # <-- Podmontowanie certyfikatów
      - ./.config/bookshelf-api-gateway/certbot-webroot:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - bookshelf-network

  bookshelf-pg:
    image: postgres:17-alpine
    container_name: bookshelf-pg
    environment:
      POSTGRES_USER: ${POSTGRES_BOOKSHELF_USER}
      POSTGRES_PASSWORD: ${POSTGRES_BOOKSHELF_PASSWORD}
      POSTGRES_DB: ${POSTGRES_BOOKSHELF_DATABASE}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - bookshelf-pg-data:/var/lib/postgresql/data
    networks:
      - bookshelf-network

  bookshelf-redis:
    image: redis:alpine
    container_name: bookshelf-redis
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped
    networks:
      - bookshelf-network

  bookshelf-rabbitmq:
    image: rabbitmq:3-management
    container_name: bookshelf-rabbitmq
    hostname: rabbitmq-node
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - bookshelf-network

  bookshelf-backend:
    build:
      context: bookshelf-backend
      dockerfile: Dockerfile
    image: bookshelf-backend
    container_name: bookshelf-backend
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx128m -Xms128m
      - POSTGRES_BOOKSHELF_HOST=bookshelf-pg
      - POSTGRES_BOOKSHELF_PORT=5432
      - POSTGRES_BOOKSHELF_DATABASE=${POSTGRES_BOOKSHELF_DATABASE}
      - POSTGRES_BOOKSHELF_USERNAME=${POSTGRES_BOOKSHELF_USER}
      - POSTGRES_BOOKSHELF_PASSWORD=${POSTGRES_BOOKSHELF_PASSWORD}
      - REDIS_HOST=bookshelf-redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=bookshelf-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
    networks:
      - bookshelf-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    depends_on:
      bookshelf-pg:
        condition: service_started

  bookshelf-frontend:
    build:
      context: bookshelf-frontend
      dockerfile: Dockerfile
    image: bookshelf-frontend
    container_name: bookshelf-frontend
    networks:
      - bookshelf-network

volumes:
  bookshelf-pg-data:
  rabbitmq-data:

networks:
  bookshelf-network: