name: Sync master back to develop

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Token For Antek
        id: antek_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.ANTEK_APP_ID }}
          private-key: ${{ secrets.ANTEK_PRIVATE_KEY }}

      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ steps.antek_token.outputs.token }}

      - name: Configure Git
        run: |
          git config user.name "Antek"
          git config user.email "antek@users.noreply.github.com"

      - name: Merge master into develop
        run: |
          git fetch origin master:master
          git merge master --no-ff -m "chore(gitflow): merge master back to develop [skip ci]"
          git push origin develop
