name: Sync master back to develop

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          # Przekazujemy Twój token – akcja zapamięta go w konfiguracji gita:
          token: ${{ secrets.SYNC_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge master into develop
        run: |
          git fetch origin master:master
          git merge master --no-ff -m "chore(gitflow): merge master back to develop [skip ci]"
          git push origin develop
